name: Mon journal
on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:

  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start tests
        run: python3 -m unittest discover -s tests

  docs:
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate and push docs
        run: |
          git config --global user.name "Dragboon"
          git config --global user.email "${{ secrets.EMAIL }}"
          git fetch
          python3 -m pydoc -w api.server && cp api.server.html doc/
          rm api.server.html
          git add .
          git commit -m "Generate docs"
          git push origin dev
        continue-on-error: true

      - name: Merge with main
        run: |
          git checkout main
          git pull origin main
          git merge dev --allow-unrelated-histories --strategy-option=theirs
          git push origin main

  release:
    needs: [tests, docs]
    runs-on: ubuntu-latest
    env:
      VERSION: 1.5
    steps:
      - name: Create-Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release${{ env.VERSION }}"
          release_name: "Release ${{ env.VERSION }}"
          draft: false
          prerelease: false

  ansible:
    needs: [tests, docs, release]
    runs-on: self-hosted

    steps:
      - name: Ansible configuration
        working-directory: /ansible-folder
        run: ansible-playbook -i inventory.yml playbook.yml  
