name: Mon journal
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start tests
        run: python3 -m unittest discover -s tests

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate docs
        run: python3 -m pydoc -w api.server && cp api.server.html doc/

      - name: Create-Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.ver }}"
          release_name: "${{ env.ver }}"
          draft: false
          prerelease: false

  ansible:
    needs: [tests]
    runs-on: self-hosted

    steps:
      - name: Ansible configuration
        working-directory: /ansible-folder
        run: ansible-playbook -i inventory.yml playbook.yml

    
