name: python_app
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start tests
        run: python3 -m unittest discover -s tests

  ansible:
    needs: [tests]
    runs-on: self-hosted

    steps:
      
      - name: Ansible configuration
        working-directory: /ansible-folder
        run: ansible-playbook -i inventory.yml playbook.yml

    
